# Archivo _config.yml básico para un sitio Jekyll en GitHub Pages

# Título del sitio
title: "Mi Página Personal"

# Descripción del sitio
description: "Este es mi sitio personal en GitHub Pages"

# URL base del sitio
baseurl: "" # Si tu sitio es el repositorio principal, déjalo vacío

# URL completa del sitio
url: "https://franker26.github.io" # Cambia a tu URL si es diferente

# Directorio de destino para los archivos generados
destination: ./_site

# Tema (opcional si usas uno específico)
theme: minima

# Permalinks para las publicaciones
permalink: /:categories/:title/

# Archivos que no deseas incluir en la generación del sitio
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

# Plugins (si estás utilizando algunos)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Otros ajustes
markdown: kramdown
highlighter: rouge
